import React from 'react'
import Head from 'next/head'
import Link from 'next/link';
import Image from 'rc-image';
import { Layout,Menu } from 'antd'

const {Header, Content, Footer} = Layout;

const MainLayout = ({children}) =>{
    return(
        <>
        <Head>
            <title>Welcome to the coding world</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
                <Header style={{background:'#ffffff'}}>
                    <Menu mode="horizontal" selectedKeys={[]}>
                        <Menu.Item key="home" style={{maxWidth:'100px'}}>
                            <Link href="/">
                                <Image
                                    width="100%"
                                    src='/next.svg'
                                    alt="coding"
                                />
                            </Link>
                        </Menu.Item>
                        <Menu.Item key="Java_project">
                            <Link href="/Java_project">
                                Java projects
                            </Link>
                        </Menu.Item>
                        <Menu.Item key="Map">
                            <Link href="/Map">
                                Mapshow
                            </Link>
                        </Menu.Item>
                    </Menu>
                </Header>
                <Content>
                    {children}
                </Content>
                <Footer style={{textAlign:'center', background:'#001529', color:'#fff'}}>
                    <section>CodingHome@{new Date().getFullYear()}. All rights reserved.</section>
                </Footer>
        </Layout>
        </>

    )
}
export default MainLayout